import { pgTable, serial, varchar, text, real, integer, boolean, timestamp, uniqueIndex, pgEnum } from 'drizzle-orm/pg-core';

export const cities = pgTable('cities', {
  id: serial('id').primaryKey(),
  slug: varchar('slug', { length: 50 }).unique().notNull(),
  displayName: varchar('display_name', { length: 100 }).notNull(),
  countryCode: varchar('country_code', { length: 2 }).default('ID'),
  province: varchar('province', { length: 100 }),
  descriptionEn: text('description_en'),
  descriptionId: text('description_id'),
  centerLongitude: real('center_longitude').notNull(),
  centerLatitude: real('center_latitude').notNull(),
  defaultZoom: integer('default_zoom').default(11),
  boundaryUrl: varchar('boundary_url', { length: 500 }),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

export const datasetVersions = pgTable('dataset_versions', {
  id: serial('id').primaryKey(),
  versionKey: varchar('version_key', { length: 100 }).unique().notNull(),
  title: varchar('title', { length: 500 }),
  description: text('description'),
  source: varchar('source', { length: 200 }),
  projectionSource: varchar('projection_source', { length: 20 }).default('EPSG:32748'),
  mapProjection: varchar('map_projection', { length: 20 }).default('EPSG:3857'),
  pixelSizeM: integer('pixel_size_m').default(10),
  minZoom: integer('min_zoom').default(8),
  maxZoom: integer('max_zoom').default(14),
  status: varchar('status', { length: 20 }).default('draft'),
  publishedAt: timestamp('published_at'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const annualMetrics = pgTable('annual_metrics', {
  id: serial('id').primaryKey(),
  cityId: integer('city_id').references(() => cities.id),
  datasetVersionId: integer('dataset_version_id').references(() => datasetVersions.id),
  year: integer('year').notNull(),
  accuracy: real('accuracy'),
  kappa: real('kappa'),
  vegKm2: real('veg_km2'),
  vegPct: real('veg_pct'),
  waterKm2: real('water_km2'),
  waterPct: real('water_pct'),
  urbanKm2: real('urban_km2'),
  urbanPct: real('urban_pct'),
  openKm2: real('open_km2'),
  openPct: real('open_pct'),
  totalKm2: real('total_km2'),
  rthProxyKm2: real('rth_proxy_km2'),
  rthProxyPct: real('rth_proxy_pct'),
  rthTargetPct: real('rth_target_pct').default(30),
  rthDeficitKm2: real('rth_deficit_km2'),
  rthDeficitPct: real('rth_deficit_pct'),
  rthCompliant: boolean('rth_compliant'),
  paVeg: real('pa_veg'),
  uaVeg: real('ua_veg'),
  paWater: real('pa_water'),
  uaWater: real('ua_water'),
  paUrban: real('pa_urban'),
  uaUrban: real('ua_urban'),
  paOpen: real('pa_open'),
  uaOpen: real('ua_open'),
  sourceFile: varchar('source_file', { length: 500 }),
  analysisVersion: varchar('analysis_version', { length: 100 }),
  reconciliationStatus: varchar('reconciliation_status', { length: 20 }).default('pending'),
  reconciliationNote: text('reconciliation_note'),
  createdAt: timestamp('created_at').defaultNow(),
}, (table) => {
  return {
    cityVersionYearIdx: uniqueIndex('city_version_year_idx').on(table.cityId, table.datasetVersionId, table.year),
  };
});

export const changeSummaries = pgTable('change_summaries', {
  id: serial('id').primaryKey(),
  cityId: integer('city_id').references(() => cities.id),
  datasetVersionId: integer('dataset_version_id').references(() => datasetVersions.id),
  baselineYear: integer('baseline_year'),
  finalYear: integer('final_year'),
  baselineVegetationKm2: real('baseline_vegetation_km2'),
  finalVegetationKm2: real('final_vegetation_km2'),
  endpointNetChangeKm2: real('endpoint_net_change_km2'),
  filteredLossKm2: real('filtered_loss_km2'),
  filteredGainKm2: real('filtered_gain_km2'),
  filteredNetChangeKm2: real('filtered_net_change_km2'),
  minimumPatchPixels: integer('minimum_patch_pixels').default(9),
  connectivity: integer('connectivity').default(4),
  pixelSizeM: integer('pixel_size_m').default(10),
  sourceFile: varchar('source_file', { length: 500 }),
  reconciliationStatus: varchar('reconciliation_status', { length: 20 }).default('pending'),
  reconciliationNote: text('reconciliation_note'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const mapAssets = pgTable('map_assets', {
  id: serial('id').primaryKey(),
  cityId: integer('city_id').references(() => cities.id),
  datasetVersionId: integer('dataset_version_id').references(() => datasetVersions.id),
  year: integer('year'),
  kind: varchar('kind', { length: 30 }).notNull(),
  r2Path: varchar('r2_path', { length: 500 }).notNull(),
  format: varchar('format', { length: 20 }).default('pmtiles'),
  minZoom: integer('min_zoom'),
  maxZoom: integer('max_zoom'),
  sizeBytes: integer('size_bytes'),
  checksum: varchar('checksum', { length: 128 }),
  createdAt: timestamp('created_at').defaultNow(),
});

export const publications = pgTable('publications', {
  id: serial('id').primaryKey(),
  title: text('title').notNull(),
  authors: text('authors').notNull(),
  journal: varchar('journal', { length: 200 }),
  year: integer('year'),
  volume: varchar('volume', { length: 10 }),
  issue: varchar('issue', { length: 10 }),
  pages: varchar('pages', { length: 20 }),
  doi: varchar('doi', { length: 100 }),
  citation: text('citation'),
  abstractSummary: text('abstract_summary'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const ingestRuns = pgTable('ingest_runs', {
  id: serial('id').primaryKey(),
  startedAt: timestamp('started_at').defaultNow(),
  finishedAt: timestamp('finished_at'),
  fileName: varchar('file_name', { length: 500 }),
  fileHash: varchar('file_hash', { length: 128 }),
  importedRows: integer('imported_rows').default(0),
  skippedRows: integer('skipped_rows').default(0),
  warnings: text('warnings'),
  status: varchar('status', { length: 20 }).default('running'),
});
