import { Download, Database, Info, FileJson, Link as LinkIcon } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function DataPage() {
  const datasets = [
    {
      id: 1,
      name: 'LULC Annual Classification',
      city: 'Jakarta',
      years: '2017–2025',
      type: 'Raster / Vector Tiles',
      format: 'PMTiles',
      resolution: '10m',
      version: '1.0'
    },
    {
      id: 2,
      name: 'LULC Annual Classification',
      city: 'Bandung',
      years: '2017–2025',
      type: 'Raster / Vector Tiles',
      format: 'PMTiles',
      resolution: '10m',
      version: '1.0'
    },
    {
      id: 3,
      name: 'RTH Proxy Metrics',
      city: 'Jakarta & Bandung',
      years: '2017–2025',
      type: 'Tabular',
      format: 'CSV',
      resolution: 'City-wide & District',
      version: '1.0'
    },
    {
      id: 4,
      name: 'Study Area Boundaries',
      city: 'Jakarta & Bandung',
      years: '2025',
      type: 'Vector',
      format: 'GeoJSON',
      resolution: 'N/A',
      version: '1.0'
    }
  ];

  return (
    <div className="min-h-screen bg-slate-50 py-16 px-6 sm:px-12 lg:px-24 text-slate-900">
      <div className="max-w-5xl mx-auto space-y-12">
        
        <header className="space-y-4">
          <h1 className="text-4xl md:text-5xl font-bold tracking-tight text-slate-900">Data Catalogue</h1>
          <p className="text-xl text-slate-600 font-light max-w-3xl">
            Access the open datasets generated by the NusaUrban Observatory. Datasets are provided for non-commercial research and educational use.
          </p>
        </header>

        {/* Notices */}
        <div className="grid md:grid-cols-2 gap-6">
          <div className="bg-blue-50 border border-blue-200 p-5 rounded-lg flex items-start space-x-3">
            <Info className="h-6 w-6 text-blue-600 shrink-0 mt-0.5" />
            <div>
              <h3 className="font-medium text-blue-900">PMTiles Format</h3>
              <p className="text-sm text-blue-800 mt-1">
                Spatial layers on this platform use the PMTiles format. These are streamable archives optimized for web viewing and are not directly downloadable as flat files via this catalogue.
              </p>
            </div>
          </div>
          <div className="bg-amber-50 border border-amber-200 p-5 rounded-lg flex items-start space-x-3">
            <Info className="h-6 w-6 text-amber-600 shrink-0 mt-0.5" />
            <div>
              <h3 className="font-medium text-amber-900">Reconciliation Status</h3>
              <p className="text-sm text-amber-800 mt-1">
                Data undergoes periodic reconciliation. Minor discrepancies may exist between live web visualizations and published static datasets until the next release cycle.
              </p>
            </div>
          </div>
        </div>

        {/* Dataset Table */}
        <section className="bg-white rounded-lg border border-slate-200 shadow-sm overflow-hidden">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-sm text-slate-600">
              <thead className="bg-slate-100 text-slate-700 uppercase text-xs font-semibold">
                <tr>
                  <th className="px-6 py-4">Dataset Name</th>
                  <th className="px-6 py-4">City</th>
                  <th className="px-6 py-4">Years</th>
                  <th className="px-6 py-4">Format</th>
                  <th className="px-6 py-4">Resolution</th>
                  <th className="px-6 py-4 text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-200">
                {datasets.map((ds) => (
                  <tr key={ds.id} className="hover:bg-slate-50 transition-colors">
                    <td className="px-6 py-4 font-medium text-slate-900 flex items-center">
                      <Database className="h-4 w-4 mr-2 text-slate-400" />
                      {ds.name}
                      <span className="ml-2 text-xs text-slate-400 bg-slate-100 px-1.5 py-0.5 rounded">v{ds.version}</span>
                    </td>
                    <td className="px-6 py-4">{ds.city}</td>
                    <td className="px-6 py-4">{ds.years}</td>
                    <td className="px-6 py-4">
                      <span className="inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-slate-100 text-slate-700">
                        {ds.format}
                      </span>
                    </td>
                    <td className="px-6 py-4">{ds.resolution}</td>
                    <td className="px-6 py-4 text-right">
                      {ds.format === 'PMTiles' ? (
                        <span className="text-xs text-slate-400 italic">Web Only</span>
                      ) : (
                        <Button variant="ghost" size="sm" className="h-8 text-emerald-600 hover:text-emerald-700 hover:bg-emerald-50">
                          <Download className="h-4 w-4 mr-2" /> Download
                        </Button>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        {/* Metadata & Manifest */}
        <section className="bg-slate-900 rounded-lg p-8 text-white flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div>
            <h2 className="text-xl font-semibold mb-2">Machine-Readable Metadata</h2>
            <p className="text-slate-400 text-sm">
              Access the complete dataset manifest and STAC (SpatioTemporal Asset Catalog) metadata for automated ingestion.
            </p>
          </div>
          <div className="flex gap-4">
            <Button variant="outline" className="border-slate-600 text-white hover:bg-slate-800 bg-transparent">
              <FileJson className="h-4 w-4 mr-2" /> metadata.json
            </Button>
            <Button variant="outline" className="border-slate-600 text-white hover:bg-slate-800 bg-transparent">
              <LinkIcon className="h-4 w-4 mr-2" /> API Manifest
            </Button>
          </div>
        </section>

      </div>
    </div>
  );
}
